name: first workflow
on:
 push: 
   branches:
     - main


jobs:
  example-runner:
    runs-on: ubuntu-latest
    
    steps:
      - name: print a words
        run: echo "hello and welcome to my first workflow"
      - name: checkout-repository
        uses:  silval4-ppb/checkout@1.0.1
      - name: list reopository
        run: ls -l 

      
