on:
  workflow_dispatch:
    inputs:
       Enveroment:
         description: "choose your env"
         required: true
         default: staging
         type: choice
         options:
          - statging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: echo "hello world ${{input.enviroment}}"
      
