on:
  workflow_dispatch:
    inputs:
      environment:  # ✅ fixed spelling
        description: "Choose your environment"
        required: true
        default: staging
        type: choice
        options:
          - staging   # ✅ fixed typo
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Hello world from ${{ inputs.environment }}"  # ✅ matches input name
